apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-dashboard
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-dashboard
          image: barryma22/flask:latest  # Ensure this image exists and is accessible
          ports:
            - containerPort: 5000

